# Generated by Django 5.0.11 on 2025-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('what_they_liked', models.TextField(verbose_name='What did you like?')),
                ('what_they_disliked', models.TextField(blank=True, null=True, verbose_name='What could be better?')),
                ('honest_review', models.TextField(verbose_name='Your honest thoughts')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('allow_publishing', models.BooleanField(default=False, help_text='Are you okay with this being published on the site?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('work', 'Work Inquiry'), ('industry_question', 'Industry Question'), ('collaboration', 'Collaboration Request'), ('consultation', '1-on-1 Consultation'), ('other', 'Other')], default='work', max_length=30),
        ),
    ]
